# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "simple_rust",
    "simple_async",
    "rust_async",
    "rust_cookbook",
    "training_code",
    "minigrep",
    "data-structure-algorithms",
    "rust-linklist"
]